#!/usr/bin/env bash

# do everything in a subshell
(
  # configuration
  CUSTOM_DOMAIN="next-amp.raha.io"

  # relevant directories
  SRC_DIR="src"
  OUT_DIR="build"
  MUSTACHE_TMP_DIR="$OUT_DIR.mustache.tmp"
  OUT_TMP_DIR="$OUT_DIR.tmp"

  # colors for output
  RED='\033[0;31m'
  GREEN='\033[0;32m'
  DARK_GRAY='\033[1;30m'
  NO_COLOR='\033[0m'

  # code from https://stackoverflow.com/a/246128/1105281
  function getScriptLocation()
  {
    local source="${BASH_SOURCE[0]}"
    while [ -h "$source" ]; do # resolve $source until the file is no longer a symlink
      local sourceDir="$( cd -P "$( dirname "$source" )" && pwd )"
      local source="$(readlink "$source")"
      [[ $source != /* ]] && source="$sourceDir/$source" # if $source was a relative symlink, we need to resolve it relative to the path where the symlink file was located
    done
    echo "$( cd -P "$( dirname "$source" )" && pwd )"
  }

  # Construct mustache partials flags
  # Assumes that we're in the project root
  # Assumes partials, in `src/partials/` directory
  function constructPartialsFlags()
  {
    local flags=""
    for partialFile in $(find ./src/partials -name '*.mustache'); do
      local flags="$(echo "$flags -p $partialFile")"
    done
    echo "$flags"
  }

  # Construct static-i18n language flags
  # Assumes that we're in the project root
  # Assumes locale files JSON, and in `locales/` directory, not in a
  # subdirectory, and no other JSON files in there
  # Assumes default is English (en)
  function constructLanguageFlags()
  {
    local flags="-l en"
    for localeFile in ./locales/*.json; do
      local localeName="${localeFile%.json}"
      local localeName="${localeName#./locales/}"
      local flags="$(echo "$flags -i $localeName")"
    done
    echo "$flags"
  }

  # cd to the root of the project
  sourceDir=$(getScriptLocation)
  cd $(dirname "$sourceDir")

  #########
  # Compile Mustache templates
  #########

  echo -e "${DARK_GRAY}Compiling Mustache templates:${NO_COLOR}"

  partialsFlags="$(constructPartialsFlags)"
  mkdir -p $MUSTACHE_TMP_DIR
  for mustacheTemplateFile in $(find ./src/pages -name '*.mustache'); do
    outPath="$MUSTACHE_TMP_DIR/${mustacheTemplateFile#./src/pages/}"
    outPath="${outPath%.mustache}.html"
    cmd="mustache $partialsFlags ./src/mustacheView.json \"$mustacheTemplateFile\" \"$outPath\""
    echo -e "\t${DARK_GRAY}Running: $cmd${NO_COLOR}"
    eval $cmd

    # if failure, delete the tmp mustache dir
    if ! [ $? -eq 0 ]; then
      echo -e "${RED}Mustache build failed${NO_COLOR}"
      rm -rf "$MUSTACHE_TMP_DIR"
    fi
  done

  echo -e "${GREEN}Compiled Mustache templates:${NO_COLOR}"

  #########
  # Compile internationalization strings
  #########

  # run static-i18n with flags determined by translations present in i18n
  langFlags="$(constructLanguageFlags)"

  cmd="./node_modules/.bin/static-i18n $langFlags -o $OUT_TMP_DIR $MUSTACHE_TMP_DIR"
  echo -e "${DARK_GRAY}Running: $cmd${NO_COLOR}"
  eval $cmd

  # in either case, delete the mustache directory
  rm -rf "$MUSTACHE_TMP_DIR"

  # if success, move the tmp output to the end result
  if [ $? -eq 0 ]; then
    echo -e "${GREEN}Build succeeded${NO_COLOR}"
    rm -rf "$OUT_DIR"
    mv "$OUT_TMP_DIR" "$OUT_DIR"
  else
    echo -e "${RED}Build failed${NO_COLOR}"
    rm -rf "$OUT_TMP_DIR"
    exit 1
  fi

  # Ensure the CNAME file is present
  echo -e "${DARK_GRAY}Adding CNAME file${NO_COLOR}"
  echo $CUSTOM_DOMAIN > build/CNAME

  # Copy assets file over
  echo -e "${DARK_GRAY}Copying assets into build dir${NO_COLOR}"
  cp -r assets build
)